name: flutlab_logcat
description: FlutLab Logcat
version: 0.0.4
homepage: https://flutlab.io

environment:
  sdk: ^3.0.0
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutlab.logcat
        pluginClass: FlutLabLogcatPlugin